"""
Django settings for www_slcschools_org project.

Generated by 'django-admin startproject' using Django 1.10.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '6h%%_qn=63q)-yay7&f-@b@qgxlc^q*oguz%qfuvu+6+hf!qj3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True 
APPEND_SLASH = True
ALLOWED_HOSTS = ['www.slcschools.org','www2.slcschools.org']
MULTISITE_EXTRA_HOSTS = ['www2.slcschools.org']
INTERNAL_IPS = '205.127.101.214'

#SAML
SAML2_AUTH = {
    # Required setting
    'METADATA_AUTO_CONF_URL': 'https://adfs.slcschools.org/FederationMetadata/2007-06/FederationMetadata.xml',

    # Optional settings below
    #'DEFAULT_NEXT_URL': '/admin/',  # Custom target redirect URL after the user get logged in. Default to /admin if not set. This setting will be overwritten if you have parameter ?next= specificed in the login URL.
    #'NEW_USER_PROFILE': {
    #    'USER_GROUPS': [],  # The default group name when a new user logs in
    #    'ACTIVE_STATUS': True,  # The default active status for new users
    #    'STAFF_STATUS': True,  # The staff status for new users
    #    'SUPERUSER_STATUS': False,  # The superuser status for new users
    #},
    'ATTRIBUTES_MAP': {  # Change Email/UserName/FirstName/LastName to corresponding SAML2 userprofile attributes.
        'email': 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress',
        'username': 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn',
        'first_name': 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname',
        'last_name': 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname',
    },
    #'TRIGGER': {
    #    'CREATE_USER': '',
    #    'BEFORE_LOGIN': '',
    #},
    'ASSERTION_URL': 'https://www2.slcschools.org', # Custom URL to validate incoming SAML requests against
}

# Custom User Model

AUTH_USER_MODEL = 'objects.User'

# Include Guardian with default authoriztions

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend', # default
    'guardian.backends.ObjectPermissionBackend',
)

# Application definition

INSTALLED_APPS = [
    # 'jet.dashboard',
    # 'jet',
    'django_saml2_auth',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'debug_toolbar',
    'guardian',
    'adminsortable2',
    'treebeard',
    'mptt',
    'ckeditor',
    'ajax_select',
    'www_slcschools_org',
    'apps.objects',
    'apps.taxonomy',
    'apps.users',
    'apps.pages',
    #'apps.images',
    #'apps.schools',
    #'apps.board',
    #'apps.news',
    #'apps.departments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'www_slcschools_org.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'www_slcschools_org', 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.common.processors.currentyear',
                'apps.taxonomy.processors.translationlinks',
                # 'apps.sitestructure.processors.breadcrumb',
                # 'apps.sitestructure.processors.mainmenu',
                # 'apps.sitestructure.processors.sitestructure',
            ],
        },
    },
]

WSGI_APPLICATION = 'www_slcschools_org.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'old': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    'default': {
      'ENGINE': 'django.db.backends.postgresql',
      'NAME': 'www_slcschools_org_dev',
      'USER': 'www',
      'PASSWORD': 'vo528wzmQ2jsa2v4fpNH',
      'HOST': 'webdb01.slcsd.net',
      'PORT': '5432',
      'CONN_MAX_AGE': None,
    },
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Denver'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
DATA_DIR = '/srv/nginx/www_slcschools_org/'
MEDIA_URL = '/'
MEDIA_ROOT = os.path.join(DATA_DIR)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(MEDIA_ROOT, 'static')

JET_DEFAULT_THEME = 'default'

JET_THEMES = [
    {
        'theme': 'default', # theme folder name
        'color': '#47bac1', # color of the theme's button in user menu
        'title': 'Default' # theme title
    },
]

JET_SIDE_MENU_COMPACT = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': 'error.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

# The cache connection to use for django-multisite.
# Default: 'default'
#CACHE_MULTISITE_ALIAS = 'multisite'

# The cache key prefix that django-multisite should use.
# If not set, defaults to the KEY_PREFIX used in the defined
# CACHE_MULTISITE_ALIAS or the default cache (empty string if not set)
#CACHE_MULTISITE_KEY_PREFIX = ''
