# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-09 16:30
from __future__ import unicode_literals

import apps.common.functions
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBanner',
            fields=[
                ('title', models.CharField(max_length=200, unique=True)),
                ('image_file', models.ImageField(max_length=2000, upload_to='', verbose_name='Image')),
                ('alttext', models.CharField(max_length=200, verbose_name='Alternative Text')),
                ('contentbanner_image_node', models.OneToOneField(db_column='contentbanner_image_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Image')),
            ],
            options={
                'db_table': 'images_contentbanner',
                'get_latest_by': 'update_date',
                'verbose_name': 'Content Banner',
                'permissions': (('trash_contentbanner', 'Can soft delete content banner'), ('restore_contentbanner', 'Can restore content banner')),
                'verbose_name_plural': 'Content Banners',
            },
            bases=('objects.image',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PageBanner',
            fields=[
                ('title', models.CharField(max_length=200, unique=True)),
                ('image_file', models.ImageField(max_length=2000, upload_to='', verbose_name='Image')),
                ('alttext', models.CharField(max_length=200, verbose_name='Alternative Text')),
                ('pagebanner_image_node', models.OneToOneField(db_column='pagebanner_image_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Image')),
            ],
            options={
                'db_table': 'images_pagebanner',
                'get_latest_by': 'update_date',
                'verbose_name': 'Page Banner',
                'permissions': (('trash_pagebanner', 'Can soft delete page banner'), ('restore_pagebanner', 'Can restore page banner')),
                'verbose_name_plural': 'Page Banners',
            },
            bases=('objects.image',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('title', models.CharField(max_length=200, unique=True)),
                ('image_file', models.ImageField(max_length=2000, upload_to=apps.common.functions.image_upload_to, verbose_name='Image')),
                ('alttext', models.CharField(max_length=200, verbose_name='Alternative Text')),
                ('thumbnail_image_node', models.OneToOneField(db_column='thumbnail_image_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Image')),
            ],
            options={
                'db_table': 'images_thumbnail',
                'get_latest_by': 'update_date',
                'verbose_name': 'Thumbnail',
                'permissions': (('trash_thumbnail', 'Can soft delete thumbnail'), ('restore_thumbnail', 'Can restore thumbnail')),
                'verbose_name_plural': 'Thumbnails',
            },
            bases=('objects.image',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
