# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-11 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentbanner',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pagebanner',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
