# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-11 19:09
from __future__ import unicode_literals

import apps.common.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20171011_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentbanner',
            name='image_file',
            field=models.ImageField(max_length=2000, upload_to=apps.common.functions.image_upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='pagebanner',
            name='image_file',
            field=models.ImageField(max_length=2000, upload_to=apps.common.functions.image_upload_to, verbose_name='Image'),
        ),
    ]
