class SchoolHelp():
  title = ("<ol>"
         "  <li class='help'>"
         "    <p class='help'>Enter the name of the school. (example: Backman Elementary School)</p>"
         "  </li>"
         "</ol>")
  intro_text = ("<ol>"
               "  <li class='help'>"
               "    <p class='help'></p>"
               "  </li>"
               "</ol>")
  building_location = ("<ol>"
                       "  <li class='help'>"
                       "    <p class='help'>Select the correct district location/address.</p>"
                       "  </li>"
                       "  <li class='help'>"
                       "    <p class='help'><strong>NOTE: </strong>If authorized you may be able to add available district locations with the plus icon to the right of the select list. This is only necessary if the location is not available in the drop down.</p>"
                       "  </li>"
                       "  <li class='help'>"
                       "    <p class='help'><strong>NOTE: </strong>If authorized you may be able to edit the selected district location with the pencil icon to the right of the select list. <strong style='color: red'> WARNING: </strong>This will edit the location details for all schools using it.</p>"
                       "  </li>"
                       "</ol>")
  main_phone  = ("<ol>"
                 "  <li class='help'>"
                 "    <p class='help'>Enter the 11 digit phone number. Numbers only. (example: 18015788599)</p>"
                 "  </li>"
                 "</ol>")
  main_fax = ("<ol>"
              "  <li class='help'>"
              "    <p class='help'>Enter the 11 digit phone number. Numbers only. (example: 18015788599)</p>"
              "  </li>"
              "</ol>")
  enrollment = ("<ol>"
              "  <li class='help'>"
              "    <p class='help'>Enter the 11 digit phone number. Numbers only. (example: 18015788599)</p>"
              "  </li>"
              "</ol>")
  school_type = ("<ol>"
                 "  <li class='help'>"
                 "    <p class='help'>Select the type of school.</p>"
                 "  </li>"
                 "  <li class='help'>"
                 "    <p class='help'><strong>NOTE: </strong>If authorized you may be able to add available school types with the plus icon to the right of the select list. This is only necessary if the school type is not available in the drop down.</p>"
                 "  </li>"
                 "  <li class='help'>"
                 "    <p class='help'><strong>NOTE: </strong>If authorized you may be able to edit the selected school type with the pencil icon to the right of the select list.<strong style='color: red'> WARNING: </strong>This will edit the school type details for all schools using it.</p>"
                 "  </li>"
                 "</ol>")
  website_url = ("<ol>"
                 "  <li class='help'>"
                 "    <p class='help'>Enter the URL for the schools website home page.</p>"
                 "  </li>"
                 "</ol>")
  boundary_map = ("<ol>"
                  "  <li class='help'>"
                  "    <p class='help'>Enter the Google Maps URL for the boundary map. This can be found in the src attribute of an embed link.</p>"
                  "  </li>"
                  "</ol>")
  open_enrollment_status = ("<ol>"
                            "  <li class='help'>"
                            "    <p class='help'>Select the current open enrollment status for the school.</p>"
                            "  </li>"
                            "  <li class='help'>"
                            "    <p class='help'><strong>NOTE: </strong>If authorized you may be able to add available open enrollment statuses with the plus icon to the right of the select list. This is only necessary if the open enrollment status is not available in the drop down.</p>"
                            "  </li>"
                            "  <li class='help'>"
                            "    <p class='help'><strong>NOTE: </strong>If authorized you may be able to edit the selected open enrollment status with the pencil icon to the right of the select list.<strong style='color: red'> WARNING: </strong>This will edit the open enrollment status details for all schools using it.</p>"
                            "  </li>"
                            "</ol>")

class SchoolTypeHelp():
   title = ("<ol>"
               "  <li class='help'>"
               "    <p class='help'>Enter the type of school. (example: Elementary School or District Charter School)</p>"
               "  </li>"
               "  <li class='help'>"
               "    <p class='help'><strong style='color: red'>WARNING: </strong>If editing an existing school type from the School Type admin page or pencil icon all schools using this school type will be updated. If you only want to change the school type of a single school please use the select list on the school edit page.</p>"
               "  </li>"
               "</ol>")
class SchoolOEStatusHelp():
  title = ("<ol>"
            "  <li class='help'>"
            "    <p class='help'>Enter the open enrollment status for the school. (example: Open or Closed)</p>"
            "  </li>"
            "  <li class='help'>"
            "    <p class='help'><strong style='color: red'>WARNING: </strong>If editing an existing status from the School Open Enrollment Status admin page or pencil icon all schools using this status will be updated. If you only want to change the status of a single school please use the select list on the school edit page.</p>"
            "  </li>"
            "</ol>")
class SchoolThumbImageHelp():
  image = ("<ol>"
           "  <li class='help'>"
           "    <p class='help'>Browse and upload an image.</p>"
           "  </li>"
           "  <li class='help'>"
           "    <p class='help'>The image must be 320x250 pixels.</p>"
           "  </li>"
           "  <li class='help'>"
           "    <p class='help'>Required Image Type: jpg.</p>"
           "  </li>"
           " </ol>")
  alttext = ("<ol>"
             "  <li class='help'>"
             "    <p class='help'>Enter a short Description of image to help screen readers or other cases where an image is not displayed.</p>"
             "  </li>"
             "</ol>")
class SchoolBannerImageHelp():
  image = ("<ol>"
           "  <li class='help'>"
           "    <p class='help'>Browse and upload an image.</p>"
           "  </li>"
           "  <li class='help'>"
           "    <p class='help'>The image must be 1280x600 pixels.</p>"
           "  </li>"
           "  <li class='help'>"
           "    <p class='help'>Required Image Type: jpg.</p>"
           "  </li>"
           " </ol>")
  alttext = ("<ol>"
             "  <li class='help'>"
             "    <p class='help'>Enter a short Description of image to help screen readers or other cases where an image is not displayed.</p>"
             "  </li>"
             "</ol>")
class SchoolAdminTypeHelp():
  title = ("<ol>"
                            "  <li class='help'>"
                            "    <p class='help'>Select the current open enrollment status for the school.</p>"
                            "  </li>"
                            "  <li class='help'>"
                            "    <p class='help'><strong>NOTE: </strong>If authorized you may be able to add available open enrollment statuses with the plus icon to the right of the select list. This is only necessary if the open enrollment status is not available in the drop down.</p>"
                            "  </li>"
                            "  <li class='help'>"
                            "    <p class='help'><strong>NOTE: </strong>If authorized you may be able to edit the selected open enrollment status with the pencil icon to the right of the select list.<strong style='color: red'> WARNING: </strong>This will edit the open enrollment status details for all schools using it.</p>"
                            "  </li>"
                            "</ol>")
