class DepartmentHelp():
  title = ("<ol>"
         "  <li class='help'>"
         "    <p class='help'>Enter the name of the department. (example: Backman Elementary Department)</p>"
         "  </li>"
         "</ol>")
  intro_text = ("<ol>"
               "  <li class='help'>"
               "    <p class='help'></p>"
               "  </li>"
               "</ol>")
  building_location = ("<ol>"
                       "  <li class='help'>"
                       "    <p class='help'>Select the correct district location/address.</p>"
                       "  </li>"
                       "  <li class='help'>"
                       "    <p class='help'><strong>NOTE: </strong>If authorized you may be able to add available district locations with the plus icon to the right of the select list. This is only necessary if the location is not available in the drop down.</p>"
                       "  </li>"
                       "  <li class='help'>"
                       "    <p class='help'><strong>NOTE: </strong>If authorized you may be able to edit the selected district location with the pencil icon to the right of the select list. <strong style='color: red'> WARNING: </strong>This will edit the location details for all departments using it.</p>"
                       "  </li>"
                       "</ol>")
  main_phone  = ("<ol>"
                 "  <li class='help'>"
                 "    <p class='help'>Enter the 11 digit phone number. Numbers only. (example: 18015788599)</p>"
                 "  </li>"
                 "</ol>")
  main_fax = ("<ol>"
              "  <li class='help'>"
              "    <p class='help'>Enter the 11 digit phone number. Numbers only. (example: 18015788599)</p>"
              "  </li>"
              "</ol>")
  enrollment = ("<ol>"
              "  <li class='help'>"
              "    <p class='help'>Enter the 11 digit phone number. Numbers only. (example: 18015788599)</p>"
              "  </li>"
              "</ol>")
  department_type = ("<ol>"
                 "  <li class='help'>"
                 "    <p class='help'>Select the type of department.</p>"
                 "  </li>"
                 "  <li class='help'>"
                 "    <p class='help'><strong>NOTE: </strong>If authorized you may be able to add available department types with the plus icon to the right of the select list. This is only necessary if the department type is not available in the drop down.</p>"
                 "  </li>"
                 "  <li class='help'>"
                 "    <p class='help'><strong>NOTE: </strong>If authorized you may be able to edit the selected department type with the pencil icon to the right of the select list.<strong style='color: red'> WARNING: </strong>This will edit the department type details for all departments using it.</p>"
                 "  </li>"
                 "</ol>")
  website_url = ("<ol>"
                 "  <li class='help'>"
                 "    <p class='help'>Enter the URL for the departments website home page.</p>"
                 "  </li>"
                 "</ol>")
  boundary_map = ("<ol>"
                  "  <li class='help'>"
                  "    <p class='help'>Enter the Google Maps URL for the boundary map. This can be found in the src attribute of an embed link.</p>"
                  "  </li>"
                  "</ol>")
  open_enrollment_status = ("<ol>"
                            "  <li class='help'>"
                            "    <p class='help'>Select the current open enrollment status for the department.</p>"
                            "  </li>"
                            "  <li class='help'>"
                            "    <p class='help'><strong>NOTE: </strong>If authorized you may be able to add available open enrollment statuses with the plus icon to the right of the select list. This is only necessary if the open enrollment status is not available in the drop down.</p>"
                            "  </li>"
                            "  <li class='help'>"
                            "    <p class='help'><strong>NOTE: </strong>If authorized you may be able to edit the selected open enrollment status with the pencil icon to the right of the select list.<strong style='color: red'> WARNING: </strong>This will edit the open enrollment status details for all departments using it.</p>"
                            "  </li>"
                            "</ol>")

class DepartmentTypeHelp():
   title = ("<ol>"
               "  <li class='help'>"
               "    <p class='help'>Enter the type of department. (example: Elementary Department or District Charter Department)</p>"
               "  </li>"
               "  <li class='help'>"
               "    <p class='help'><strong style='color: red'>WARNING: </strong>If editing an existing department type from the Department Type admin page or pencil icon all departments using this department type will be updated. If you only want to change the department type of a single department please use the select list on the department edit page.</p>"
               "  </li>"
               "</ol>")
class DepartmentOEStatusHelp():
  title = ("<ol>"
            "  <li class='help'>"
            "    <p class='help'>Enter the open enrollment status for the department. (example: Open or Closed)</p>"
            "  </li>"
            "  <li class='help'>"
            "    <p class='help'><strong style='color: red'>WARNING: </strong>If editing an existing status from the Department Open Enrollment Status admin page or pencil icon all departments using this status will be updated. If you only want to change the status of a single department please use the select list on the department edit page.</p>"
            "  </li>"
            "</ol>")
class DepartmentThumbImageHelp():
  image = ("<ol>"
           "  <li class='help'>"
           "    <p class='help'>Browse and upload an image.</p>"
           "  </li>"
           "  <li class='help'>"
           "    <p class='help'>The image must be 320x250 pixels.</p>"
           "  </li>"
           "  <li class='help'>"
           "    <p class='help'>Required Image Type: jpg.</p>"
           "  </li>"
           " </ol>")
  alttext = ("<ol>"
             "  <li class='help'>"
             "    <p class='help'>Enter a short Description of image to help screen readers or other cases where an image is not displayed.</p>"
             "  </li>"
             "</ol>")
class DepartmentBannerImageHelp():
  image = ("<ol>"
           "  <li class='help'>"
           "    <p class='help'>Browse and upload an image.</p>"
           "  </li>"
           "  <li class='help'>"
           "    <p class='help'>The image must be 1280x600 pixels.</p>"
           "  </li>"
           "  <li class='help'>"
           "    <p class='help'>Required Image Type: jpg.</p>"
           "  </li>"
           " </ol>")
  alttext = ("<ol>"
             "  <li class='help'>"
             "    <p class='help'>Enter a short Description of image to help screen readers or other cases where an image is not displayed.</p>"
             "  </li>"
             "</ol>")
class DepartmentAdminTypeHelp():
  title = ("<ol>"
                            "  <li class='help'>"
                            "    <p class='help'>Select the current open enrollment status for the department.</p>"
                            "  </li>"
                            "  <li class='help'>"
                            "    <p class='help'><strong>NOTE: </strong>If authorized you may be able to add available open enrollment statuses with the plus icon to the right of the select list. This is only necessary if the open enrollment status is not available in the drop down.</p>"
                            "  </li>"
                            "  <li class='help'>"
                            "    <p class='help'><strong>NOTE: </strong>If authorized you may be able to edit the selected open enrollment status with the pencil icon to the right of the select list.<strong style='color: red'> WARNING: </strong>This will edit the open enrollment status details for all departments using it.</p>"
                            "  </li>"
                            "</ol>")
