# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-18 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20171018_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcelink',
            options={'get_latest_by': 'update_date', 'permissions': (('trash_resourcelink', 'Can soft delete resource link'), ('restore_resourcelink', 'Can restore resource link')), 'verbose_name': 'Resource Link', 'verbose_name_plural': 'Resource Links'},
        ),
    ]
