# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-04 16:07
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_user_node', models.OneToOneField(db_column='employee_user_node', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employees',
                'verbose_name': 'Employee',
                'db_table': 'users_employee',
                'get_latest_by': 'create_date',
            },
            bases=('objects.user',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('system_user_node', models.OneToOneField(db_column='system_user_node', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'System',
                'verbose_name': 'System',
                'db_table': 'users_system',
                'get_latest_by': 'create_date',
            },
            bases=('objects.user',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
