# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-12 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('objects', '0002_directoryentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAdministrator',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('schooladministrator_directoryentry_node', models.OneToOneField(db_column='schooladministrator_directoryentry_node', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.DirectoryEntry')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directoryenties_schooladministrator_employee', to='users.Employee')),
            ],
            options={
                'db_table': 'directoryenties_schooladministrator',
                'verbose_name_plural': 'School Administrators',
                'verbose_name': 'School Administrator',
                'get_latest_by': 'create_date',
            },
            bases=('objects.directoryentry',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
