# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-13 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_schooladministratortype'),
        ('directoryentries', '0002_auto_20171013_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooladministrator',
            name='schooladministratortype',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='directoryenties_schooladministrator_schooladministratortype', to='taxonomy.SchoolAdministratorType'),
            preserve_default=False,
        ),
    ]
