# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-04 16:07
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('title', models.CharField(max_length=200, unique=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, help_text="<ol>  <li class='help'>    <p class='help'></p>  </li></ol>", null=True)),
                ('page_page_node', models.OneToOneField(db_column='page_page_node', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Page')),
            ],
            options={
                'verbose_name_plural': 'Pages',
                'verbose_name': 'Page',
                'db_table': 'pages_page',
                'permissions': (('trash_page', 'Can soft delete page'), ('restore_page', 'Can restore page')),
                'get_latest_by': 'update_date',
            },
            bases=('objects.page',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('title', models.CharField(max_length=200, unique=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('main_phone', models.CharField(max_length=11)),
                ('main_fax', models.CharField(max_length=11)),
                ('enrollment', models.PositiveIntegerField()),
                ('website_url', models.URLField(max_length=2048)),
                ('scc_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('boundary_map', models.URLField(blank=True, max_length=2048, null=True)),
                ('school_page_node', models.OneToOneField(db_column='school_page_node', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Page')),
                ('building_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages_school_building_location', to='taxonomy.Location')),
                ('openenrollmentstatus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages_school_openenrollmentstatus', to='taxonomy.OpenEnrollmentStatus')),
                ('schooltype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages_school_schooltype', to='taxonomy.SchoolType')),
            ],
            options={
                'verbose_name_plural': 'Schools',
                'verbose_name': 'School',
                'db_table': 'pages_school',
                'permissions': (('trash_school', 'Can soft delete school'), ('restore_school', 'Can restore school')),
                'get_latest_by': 'update_date',
            },
            bases=('objects.page',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
