# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-13 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_page_node',
            field=models.OneToOneField(db_column='page_page_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Page'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_page_node',
            field=models.OneToOneField(db_column='school_page_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Page'),
        ),
    ]
