# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-13 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_directoryentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directoryentry',
            name='directoryentry_node',
            field=models.OneToOneField(db_column='directoryentry_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Node'),
        ),
    ]
