# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-13 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_auto_20171013_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_node',
            field=models.OneToOneField(db_column='image_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Node'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_node',
            field=models.OneToOneField(db_column='page_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Node'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='taxonomy_node',
            field=models.OneToOneField(db_column='taxonomy_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Node'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_node',
            field=models.OneToOneField(db_column='user_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Node'),
        ),
    ]
