# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-04 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('title', models.CharField(db_column='city', max_length=200, unique=True)),
                ('city_taxonomy_node', models.OneToOneField(db_column='city_taxonomy_node', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Taxonomy')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'verbose_name': 'City',
                'db_table': 'taxonomy_city',
                'permissions': (('trash_city', 'Can soft delete city'), ('restore_city', 'Can restore city')),
                'get_latest_by': 'update_date',
            },
            bases=('objects.taxonomy',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('title', models.CharField(db_column='language', max_length=200, unique=True, verbose_name='Language')),
                ('native_language', models.CharField(max_length=200, unique=True, verbose_name='Native Language Spelling')),
                ('language_code', models.CharField(max_length=5, unique=True, verbose_name='Language Code')),
                ('language_taxonomy_node', models.OneToOneField(db_column='language_taxonomy_node', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Taxonomy')),
            ],
            options={
                'verbose_name_plural': 'Languages',
                'verbose_name': 'Language',
                'db_table': 'taxonomy_language',
                'permissions': (('trash_language', 'Can soft delete language'), ('restore_language', 'Can restore language')),
                'get_latest_by': 'update_date',
            },
            bases=('objects.taxonomy',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('title', models.CharField(db_column='location', max_length=200, unique=True)),
                ('street_address', models.CharField(max_length=200, unique=True)),
                ('google_place', models.URLField(blank=True, max_length=2048, null=True)),
                ('location_taxonomy_node', models.OneToOneField(db_column='location_taxonomy_node', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Taxonomy')),
                ('location_city', models.ForeignKey(db_column='city', on_delete=django.db.models.deletion.PROTECT, related_name='taxonomy_location_city', to='taxonomy.City')),
            ],
            options={
                'verbose_name_plural': 'Locations',
                'verbose_name': 'Location',
                'db_table': 'taxonomy_location',
                'permissions': (('trash_location', 'Can soft delete location'), ('restore_location', 'Can restore location')),
                'get_latest_by': 'update_date',
            },
            bases=('objects.taxonomy',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OpenEnrollmentStatus',
            fields=[
                ('title', models.CharField(max_length=200, unique=True)),
                ('openenrollmentstatus_taxonomy_node', models.OneToOneField(db_column='openenrollmentstatus_taxonomy_node', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Taxonomy')),
            ],
            options={
                'verbose_name_plural': 'Open Enrollment Statuses',
                'verbose_name': 'Open Enrollment Status',
                'db_table': 'taxonomy_openenrollmentstatus',
                'permissions': (('trash_openenrollmentstatus', 'Can soft delete school open enrollment status'), ('restore_openenrollmentstatus', 'Can restore school open enrollment status')),
                'get_latest_by': 'update_date',
            },
            bases=('objects.taxonomy',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolType',
            fields=[
                ('title', models.CharField(max_length=200, unique=True)),
                ('schooltype_taxonomy_node', models.OneToOneField(db_column='schooltype_taxonomy_node', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Taxonomy')),
            ],
            options={
                'verbose_name_plural': 'School Types',
                'verbose_name': 'School Type',
                'db_table': 'taxonomy_schooltype',
                'permissions': (('trash_schooltype', 'Can soft delete school type'), ('restore_schooltype', 'Can restore school type')),
                'get_latest_by': 'update_date',
            },
            bases=('objects.taxonomy',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('title', models.CharField(db_column='state', max_length=200, unique=True)),
                ('state_taxonomy_node', models.OneToOneField(db_column='state_taxonomy_node', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Taxonomy')),
            ],
            options={
                'verbose_name_plural': 'States',
                'verbose_name': 'State',
                'db_table': 'taxonomy_state',
                'permissions': (('trash_state', 'Can soft delete state'), ('restore_state', 'Can restore state')),
                'get_latest_by': 'update_date',
            },
            bases=('objects.taxonomy',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TranslationType',
            fields=[
                ('title', models.CharField(db_column='translationtype', max_length=200, unique=True, verbose_name='Translation Link Type')),
                ('translationtype_taxonomy_node', models.OneToOneField(db_column='translationtype_taxonomy_node', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Taxonomy')),
            ],
            options={
                'verbose_name_plural': 'Translation Types',
                'verbose_name': 'Translation Type',
                'db_table': 'taxonomy_translationtype',
                'permissions': (('trash_translationtype', 'Can soft delete translation type'), ('restore_translationtype', 'Can restore translation type')),
                'get_latest_by': 'update_date',
            },
            bases=('objects.taxonomy',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('title', models.CharField(db_column='zipcode', max_length=200, unique=True)),
                ('zipcode_taxonomy_node', models.OneToOneField(db_column='zipcode_taxonomy_node', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Taxonomy')),
            ],
            options={
                'verbose_name_plural': 'ZIP Codes',
                'verbose_name': 'ZIP Code',
                'db_table': 'taxonomy_zipcode',
                'permissions': (('trash_zipcode', 'Can soft delete zipcode'), ('restore_zipcode', 'Can restore zipcode')),
                'get_latest_by': 'update_date',
            },
            bases=('objects.taxonomy',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='location_state',
            field=models.ForeignKey(db_column='state', on_delete=django.db.models.deletion.PROTECT, related_name='taxonomy_location_state', to='taxonomy.State'),
        ),
        migrations.AddField(
            model_name='location',
            name='location_zipcode',
            field=models.ForeignKey(db_column='zipcode', on_delete=django.db.models.deletion.PROTECT, related_name='taxonomy_location_zipcode', to='taxonomy.Zipcode'),
        ),
        migrations.AddField(
            model_name='language',
            name='language_translationtype',
            field=models.ForeignKey(db_column='translationtype', on_delete=django.db.models.deletion.PROTECT, related_name='taxonomy_language_translationtype', to='taxonomy.TranslationType', verbose_name='Translation Type'),
        ),
    ]
