# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-13 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_taxonomy_node',
            field=models.OneToOneField(db_column='city_taxonomy_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Taxonomy'),
        ),
        migrations.AlterField(
            model_name='language',
            name='language_taxonomy_node',
            field=models.OneToOneField(db_column='language_taxonomy_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Taxonomy'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_taxonomy_node',
            field=models.OneToOneField(db_column='location_taxonomy_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Taxonomy'),
        ),
        migrations.AlterField(
            model_name='openenrollmentstatus',
            name='openenrollmentstatus_taxonomy_node',
            field=models.OneToOneField(db_column='openenrollmentstatus_taxonomy_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Taxonomy'),
        ),
        migrations.AlterField(
            model_name='schooltype',
            name='schooltype_taxonomy_node',
            field=models.OneToOneField(db_column='schooltype_taxonomy_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Taxonomy'),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_taxonomy_node',
            field=models.OneToOneField(db_column='state_taxonomy_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Taxonomy'),
        ),
        migrations.AlterField(
            model_name='translationtype',
            name='translationtype_taxonomy_node',
            field=models.OneToOneField(db_column='translationtype_taxonomy_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Taxonomy'),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='zipcode_taxonomy_node',
            field=models.OneToOneField(db_column='zipcode_taxonomy_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Taxonomy'),
        ),
    ]
