# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-13 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_auto_20171013_1432'),
        ('taxonomy', '0002_auto_20171013_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAdministratorType',
            fields=[
                ('title', models.CharField(db_index=True, max_length=200, unique=True)),
                ('schooladministratortype_taxonomy_node', models.OneToOneField(db_column='schooladministratortype_taxonomy_node', editable=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.Taxonomy')),
            ],
            options={
                'verbose_name_plural': 'School Administrator Types',
                'db_table': 'taxonomy_schooladministratortype',
                'verbose_name': 'School Administrator Type',
                'get_latest_by': 'update_date',
                'permissions': (('trash_schooladministratortype', 'Can soft delete school administrator type'), ('restore_schooladministratortype', 'Can restore school administrator type')),
            },
            bases=('objects.taxonomy',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
